### ISSUE TITLE
npm run build:web的时候出现了错误

### ISSUE THREAD

**Issue by Smithjoppa** [xiaozhu188/electron-vue-cloud-music#1]
<--- Last few GCs --->

[13016:0x102c00000]   112324 ms: Mark-sweep 1309.8 (1450.7) -> 1305.0 (1453.2) MB, 2477.0 / 0.0 ms  (average mu = 0.103, current mu = 0.015) allocation failure scavenge might not succeed
[13016:0x102c00000]   115329 ms: Mark-sweep 1315.2 (1453.2) -> 1310.7 (1453.2) MB, 2948.1 / 0.0 ms  (average mu = 0.059, current mu = 0.019) allocation failure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x235dc5edbe3d]
    1: StubFrame [pc: 0x235dc5e934b0]
Security context: 0x3c39d531e6e9 <JSObject>
    2: create [0x3c39a424de39] [/Users/smithcll/project/electron/electron-vue-cloud-music-master/node_modules/babel-traverse/lib/context.js:~67] [pc=0x235dc73b69a8](this=0x3c390a78c2e1 <TraversalContext map = 0x3c396c9d9e39>,node=0x3c3945c638a1 <Node map = 0x3c396c9a8bb9>,obj=0x3c3945c638a1 <Node map = 0x3c396c9a8bb9>,ke...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10003cf99 node::Abort() [/usr/local/bin/node]
 2: 0x10003d1a3 node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0x1001b7835 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0x100585682 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 5: 0x100588155 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/usr/local/bin/node]
 6: 0x100583fff v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
 7: 0x1005821d4 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
 8: 0x10058ea6c v8::internal::Heap::AllocateRawWithLigthRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/bin/node]
 9: 0x10058eaef v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/bin/node]
10: 0x10055e434 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/usr/local/bin/node]
11: 0x1007e6714 v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
12: 0x235dc5edbe3d 
13: 0x235dc5e934b0 
14: 0x235dc73b69a8 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-vue-cloud-music@1.0.12 build:web: `cross-env BUILD_TARGET=web node .electron-vue/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-vue-cloud-music@1.0.12 build:web script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by xiaozhu188** [comment]
程序集成了node，不支持打包web
