### ISSUE TITLE
切换选项卡能保存页面的状态吗？

### ISSUE THREAD

**Issue by GanZhiXiong** [xiaozhu188/electron-vue-cloud-music#3]
# 操作步骤如下
## 1、发现音乐滚动到最底下
![image](https://user-images.githubusercontent.com/27394631/67621786-dd418000-f845-11e9-8451-e122f38abca1.png)

## 2、点击本地音乐
![image](https://user-images.githubusercontent.com/27394631/67621797-edf1f600-f845-11e9-8548-18b08935f37f.png)

## 3、点击发现音乐
![image](https://user-images.githubusercontent.com/27394631/67621812-019d5c80-f846-11e9-8493-b2773f5f56a5.png)

### 此时发现音乐是进行了重新刷新了吗？因为滚动条不在原来的位置了，能否做成保存页面状态吗？

**Comment by xiaozhu188** [comment]
没有重新刷新。只是我在实例化Router的时候设置了scrollBehavior

**Comment by GanZhiXiong** [comment]
那能不能做到回到之前的页面时候，滚动条还是在原来的位置？
