### ISSUE TITLE
大佬，你用的vscode还是webstrom啊？

### ISSUE THREAD

**Issue by GanZhiXiong** [xiaozhu188/electron-vue-cloud-music#5]

**Comment by xiaozhu188** [comment]
vscode

**Comment by wangqiaoqiaogithub** [comment]
@xiaozhu188 正确打包web版当前项目的姿势求告知:git:

**Comment by ducksouls** [comment]
@xiaozhu188 想知道用的vue-cli3还是vue-cli2,用的是simulateedGRED/electron-vue还是Vue CLI Plugin Electron Builder, 万分感谢

**Comment by xiaozhu188** [comment]
@ducksouls Vue CLI Plugin Electron Builder
