### ISSUE TITLE
你好，新的vue-electron脚手架搭建教程可以分享一下吗？

### ISSUE THREAD

**Issue by zshuaia** [xiaozhu188/electron-vue-cloud-music#7]
你好，新的vue-electron脚手架搭建教程可以分享一下吗？
最近项目用到electron,还是用的以前的VUE-CLI2的脚手架，可以分享一下你这个脚手架的demo吗，万分感谢！

**Comment by DongLee0504** [comment]
好像用的是这个 https://github.com/nklayman/vue-cli-plugin-electron-builder
