### ISSUE TITLE
Mac界面初始化Bug

### ISSUE THREAD

**Issue by GeekEast** [xiaozhu188/electron-vue-cloud-music#8]
![image](https://user-images.githubusercontent.com/24806887/75305460-1a6e5b00-5896-11ea-91b1-96dd3462fc08.png)

**Comment by xiaozhu188** [comment]
目前还没有对mac做适配

**Comment by xiaozhu188** [comment]
@GeekEast  目前还没有对mac做适配  [5f2d509](https://github.com/xiaozhu188/electron-vue-cloud-music/commit/5f2d509a1fab689a2cf93a5f76a737ce840efdb5)
